feat: add paused state to online DDL scheduler (#357)
* feat: add pause, unpause, pause all, unpause all sql to onlineDDL

Signed-off-by: newborn22 <953950914@qq.com>

* fix: fix some bugs, clear TODOs, and clarify when can users pause an onlineDDL

Signed-off-by: newborn22 <953950914@qq.com>

* test: add e2e test

Signed-off-by: newborn22 <953950914@qq.com>

* fix: add failpoint config to test yml

Signed-off-by: newborn22 <953950914@qq.com>

* fix: fix e2e test

Signed-off-by: newborn22 <953950914@qq.com>

* fix: Organize code comments, waitting code reviews

Signed-off-by: newborn22 <953950914@qq.com>

* fix: change yaml config by modify .tpl files instead of modify .yml files directly

Signed-off-by: newborn22 <953950914@qq.com>

* fix: replace old yml files with new ones in archive folder

Signed-off-by: newborn22 <953950914@qq.com>

* fix: add failpoint in unit_test.tpl

Signed-off-by: newborn22 <953950914@qq.com>

---------

Signed-off-by: newborn22 <953950914@qq.com>

diff --git a/.github/workflows/archive/unit_test_mysql57.yml b/.github/workflows/archive/unit_test_mysql57.yml
--- a/.github/workflows/archive/unit_test_mysql57.yml
+++ b/.github/workflows/archive/unit_test_mysql57.yml
@@ -1,22 +1,21 @@
 # DO NOT MODIFY: THIS FILE IS GENERATED USING "make generate_ci_workflows"
 
-name: Cluster (21)
+name: Unit Test (mysql57)
 on:
-#  pull_request:
+  pull_request:
   workflow_dispatch:
   push:
     branches:
       - main
 concurrency:
-  group: format('{0}-{1}', ${{ github.ref }}, 'Cluster (21)')
+  group: format('{0}-{1}', ${{ github.ref }}, 'Unit Test (mysql57)')
   cancel-in-progress: true
 
 env:
   GITHUB_PR_HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
 
 jobs:
-  build:
-    name: Run endtoend tests on Cluster (21)
+  test:
     runs-on: ubuntu-22.04
 
     steps:
@@ -48,8 +47,8 @@ jobs:
       with:
         token: ''
         filters: |
-          end_to_end:
-            - 'go/**/*.go'
+          unit_tests:
+            - 'go/**'
             - 'test.go'
             - 'Makefile'
             - 'build.env'
@@ -59,73 +58,88 @@ jobs:
             - 'tools/**'
             - 'config/**'
             - 'bootstrap.sh'
-            - '.github/workflows/cluster_endtoend_21.yml'
+            - '.github/workflows/unit_test_mysql57.yml'
 
     - name: Set up Go
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
       uses: actions/setup-go@v3
       with:
         go-version: 1.20.1
 
     - name: Set up python
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
       uses: actions/setup-python@v4
 
     - name: Tune the OS
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
       run: |
-        # Limit local port range to not use ports that overlap with server side
-        # ports that we listen on.
         sudo sysctl -w net.ipv4.ip_local_port_range="22768 65535"
         # Increase the asynchronous non-blocking I/O. More information at https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_use_native_aio
         echo "fs.aio-max-nr = 1048576" | sudo tee -a /etc/sysctl.conf
         sudo sysctl -p /etc/sysctl.conf
 
     - name: Get dependencies
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
       run: |
-        
+        export DEBIAN_FRONTEND="noninteractive"
+        sudo apt-get update
+
+        # Uninstall any previously installed MySQL first
+        sudo systemctl stop apparmor
+        sudo DEBIAN_FRONTEND="noninteractive" apt-get remove -y --purge mysql-server mysql-client mysql-common
+        sudo apt-get -y autoremove
+        sudo apt-get -y autoclean
+        sudo deluser mysql
+        sudo rm -rf /var/lib/mysql
+        sudo rm -rf /etc/mysql
+
         # Get key to latest MySQL repo
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29
-        # Setup MySQL 8.0
+
+        # mysql57
         wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
-        echo mysql-apt-config mysql-apt-config/select-server select mysql-8.0 | sudo debconf-set-selections
+        # Bionic packages are still compatible for Jammy since there's no MySQL 5.7
+        # packages for Jammy.
+        echo mysql-apt-config mysql-apt-config/repo-codename select bionic | sudo debconf-set-selections
+        echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
         sudo DEBIAN_FRONTEND="noninteractive" dpkg -i mysql-apt-config*
         sudo apt-get update
-        # Install everything else we need, and configure
-        sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget eatmydata xz-utils libncurses5
+        sudo DEBIAN_FRONTEND="noninteractive" apt-get install -y mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7* libncurses5
 
+        sudo apt-get install -y make unzip g++ curl git wget ant openjdk-11-jdk eatmydata
         sudo service mysql stop
-        sudo service etcd stop
+        sudo bash -c "echo '/usr/sbin/mysqld { }' > /etc/apparmor.d/usr.sbin.mysqld" # https://bugs.launchpad.net/ubuntu/+source/mariadb-10.1/+bug/1806263
         sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
-        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
-        go mod download
+        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld || echo "could not remove mysqld profile"
 
+        mkdir -p dist bin
+        curl -L https://github.com/coreos/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz | tar -zxC dist
+        mv dist/etcd-v3.3.10-linux-amd64/{etcd,etcdctl} bin/
+
+        go mod download
+        go install golang.org/x/tools/cmd/goimports@latest
+        
         # install JUnit report formatter
         go install github.com/vitessio/go-junit-report@HEAD
 
-    - name: Run cluster endtoend test
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
-      timeout-minutes: 45
+    - name: Run make tools
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
       run: |
-        # We set the VTDATAROOT to the /tmp folder to reduce the file path of mysql.sock file
-        # which musn't be more than 107 characters long.
-        export VTDATAROOT="/tmp/"
-        source build.env
+        make tools
 
-        set -x
-
-        # run the tests however you normally do, then produce a JUnit XML file
+    - name: Run test
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true'
+      timeout-minutes: 30
+      run: |
         # failpoint
         chmod 755 ./test/failpoint/failpoints.sh && source ./test/failpoint/failpoints.sh
         echo "GO_FAILPOINTS=$GO_FAILPOINTS" >> $GITHUB_OUTPUT
         make failpoint-enable
-        eatmydata -- go run test.go -docker=false -follow -shard 21 | tee -a output.txt | go-junit-report -set-exit-code > report.xml
+        eatmydata -- make unit_test | tee -a output.txt | go-junit-report -set-exit-code > report.xml
         make failpoint-disable
 
     - name: Print test output and Record test result
-      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true' && always()
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.unit_tests == 'true' && always()
       run: |
-
         # print test output
         cat output.txt
