feat: build image ci (#573)
* fix: test build img

* fix:Fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

* fix: fix

Signed-off-by: newborn22 <953950914@qq.com>

* fix: fix

Signed-off-by: newborn22 <953950914@qq.com>

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix:fix

* fix: fix

* fix: fix

* chore: add todo

Signed-off-by: earayu <earayu@163.com>

* fix: print wescale log; try to fix path error

* fix: replace old mtr docker yaml

---------

Signed-off-by: newborn22 <953950914@qq.com>
Signed-off-by: earayu <earayu@163.com>
Co-authored-by: earayu <earayu@163.com>

diff --git a/.github/workflows/cluster_endtoend_mtr_docker.yml b/.github/workflows/cluster_endtoend_mtr_docker.yml
--- a/.github/workflows/cluster_endtoend_mtr_docker.yml
+++ b/.github/workflows/cluster_endtoend_mtr_docker.yml
@@ -1,4 +1,5 @@
 name: "MTR Test - Ubuntu Docker Cluster"
+
 on:
   pull_request:
     types: [opened, synchronize, reopened]
@@ -9,13 +10,37 @@ on:
     tags:
       - '*'
   workflow_dispatch:
+
+env:
+  IMAGE_NAME: wescale_ci_image
+  REGISTRY: ghcr.io
+  IMAGE_TAG: test-${{ github.sha }}
+  MYSQL_ROOT_PASSWORD: passwd
+  MYSQL_ROOT_HOST: "%"
+  MYSQL_PORT: 3306
+  WESCALE_PORT: 15306
+  MYSQL_VERSION: 8.0.32
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}-mtr
   cancel-in-progress: true
 
 jobs:
+  build-image:
+    permissions:
+      contents: read
+      packages: write
+    uses: ./.github/workflows/build_image.yml
+    with:
+      branch: ${{ github.ref }}
+      image_name: ${{ github.repository_owner }}/wescale_ci_image
+      tags: test-${{ github.sha }}
+      registry: ghcr.io
+      platforms: linux/amd64
+
   setup:
     name: "MTR Test - Ubuntu Docker Cluster"
+    needs: build-image
     runs-on: ubuntu-latest
 
     steps:
@@ -33,30 +58,65 @@ jobs:
         if: steps.skip-workflow.outputs.skip-workflow == 'false'
         uses: actions/checkout@v3
 
-      - name: Set up Go
-        if: steps.skip-workflow.outputs.skip-workflow == 'false'
-        uses: actions/setup-go@v3
+      - name: Login to registry
+        uses: docker/login-action@v3
         with:
-          go-version: 1.23
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ github.token }}
 
-      - name: Compile source
-        if: steps.skip-workflow.outputs.skip-workflow == 'false'
-        timeout-minutes: 30
+
+      - name: Set up cluster
         run: |
-          # install etcd
-          BUILD_CHROME=0 BUILD_JAVA=0 BUILD_CONSUL=0 BUILD_K3S=0 BUILD_ETCD=1 ./bootstrap.sh
+          CONTAINER_NAME="mysql-server"
+          DATA_DIR="$(pwd)/vtdataroot/mysql"
+          CONFIG_FILE="$DATA_DIR/my.cnf"
+          MYSQL_IMG="mysql/mysql-server:${{ env.MYSQL_VERSION }}"
+          WESCALE_CI_IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
           
-          make failpoint-enable
-          make build
-          make failpoint-disable
-
-      - name: Start MySQL-Server & WeScale
-        if: steps.skip-workflow.outputs.skip-workflow == 'false'
-        run: |
-          export PATH=$PATH:$(pwd)/bin
-          cd ./examples/wesql-server
-          ./start_mysql_server.sh
-          ./init_single_node_cluster.sh 2>&1 | tee init_script_logs.txt &
+          mkdir -p "$DATA_DIR/data"
+          mkdir -p "$DATA_DIR/log"
+          
+          if [ ! -f "$CONFIG_FILE" ]; then
+          cat <<EOL > "$CONFIG_FILE"
+          [mysqld]
+          port=${{ env.MYSQL_PORT }}
+          bind-address=0.0.0.0
+          log-bin=binlog
+          gtid_mode=ON
+          enforce_gtid_consistency=ON
+          log_replica_updates=ON
+          binlog_format=ROW
+          datadir=/data/mysql/data
+          log-error=/data/mysql/log/mysqld-error.log
+          EOL
+          fi
+          
+          chmod -R 777 "$DATA_DIR"
+          chmod 644 "$CONFIG_FILE"
+          
+          docker network create my-network
+          
+          docker run -itd --name $CONTAINER_NAME \
+          --network my-network \
+          -p ${{ env.MYSQL_PORT }}:${{ env.MYSQL_PORT }} \
+          -v "$DATA_DIR":/data/mysql \
+          -v "$CONFIG_FILE":/etc/my.cnf \
+          -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }} \
+          -e MYSQL_ROOT_HOST="${{ env.MYSQL_ROOT_HOST }}" \
+          $MYSQL_IMG
+          
+          docker run -itd \
+          --name wescale \
+          --network my-network \
+          -w /vt/examples/wesql-server \
+          -e MYSQL_ROOT_USER=root \
+          -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }} \
+          -e MYSQL_PORT=${{ env.MYSQL_PORT }} \
+          -e MYSQL_HOST=mysql-server \
+          -p ${{ env.WESCALE_PORT }}:${{ env.WESCALE_PORT }} \
+          $WESCALE_CI_IMAGE \
+          /vt/examples/wesql-server/init_single_node_cluster.sh
 
       - name: Checkout mysql-tester code
         if: steps.skip-workflow.outputs.skip-workflow == 'false'
@@ -76,18 +136,49 @@ jobs:
         if: steps.skip-workflow.outputs.skip-workflow == 'false'
         run: |
           cd ./mysql-tester && \
-          eatmydata -- ./bin/mysql-tester -user root -port 15306 -path testcase/wesql-scale 2>&1 | tee -a output.txt
+          eatmydata -- ./bin/mysql-tester -user root -port ${{ env.WESCALE_PORT }} -path testcase/wesql-scale 2>&1 | tee -a output.txt
           
-          # check if any test failed
-          if grep -q -- 'level=error' ./mysql-tester/output.txt; then
+          if grep -q -- 'level=error' output.txt; then
               echo "Testcase is failed"
               exit 1
           else
               echo "Testcase is successful"
           fi
-
-      - name: Print WeScale Logs
-        if: steps.skip-workflow.outputs.skip-workflow == 'false'
+      - name: Print Wescale logs
         run: |
-          docker logs mysql-server
-          cat ./examples/wesql-server/init_script_logs.txt
+          docker logs wescale
+
+      - name: Clean up
+        if: always()
+        run: |
+          TOKEN="${{ github.token }}"
+          OWNER="${{ github.repository_owner }}"
+          PACKAGE_NAME="${{ env.IMAGE_NAME }}"
+          TAG="${{ env.IMAGE_TAG }}"
+
+          VERSIONS_JSON=$(curl -s \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME/versions")
+
+          PACKAGE_VERSION_ID=$(echo "$VERSIONS_JSON" | jq -r ".[] | select(.metadata.container.tags[] | contains(\"$TAG\")) | .id")
+
+          if [ ! -z "$PACKAGE_VERSION_ID" ]; then
+            echo "Found image version ID: $PACKAGE_VERSION_ID"
+
+            DELETE_RESPONSE=$(curl -X DELETE -s -H "Authorization: Bearer $TOKEN" \
+              -H "Accept: application/vnd.github+json" \
+              "https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME/versions/$PACKAGE_VERSION_ID")
+
+            if [ -z "$DELETE_RESPONSE" ]; then
+              echo "✅ Successfully deleted image version: $PACKAGE_VERSION_ID"
+            else
+              echo "❌ Failed to delete image version. Response: $DELETE_RESPONSE"
+              exit 1
+            fi
+          else
+            echo "❌ Could not find image version with tag: $TAG"
+            echo "Available versions:"
+            echo "$VERSIONS_JSON" | jq -r '.[].names'
+            exit 1
+          fi
