chore: fix CI for wesql
Signed-off-by: earayu <earayu@163.com>

diff --git a/.github/workflows/cluster_endtoend_wesql.yml b/.github/workflows/cluster_endtoend_wesql.yml
--- a/.github/workflows/cluster_endtoend_wesql.yml
+++ b/.github/workflows/cluster_endtoend_wesql.yml
@@ -137,3 +137,13 @@ jobs:
 
         # print test output
         cat output.txt
+    - name: Check test results
+      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true' && always()
+      run: |
+          # check if there are no '0 FAILED' in output.txt, then testcase is successful, otherwise it is failed
+          if grep -q '0 FAILED' output.txt; then
+              echo "Testcase is successful"
+          else
+              echo "Testcase is failed"
+              exit 1
+          fi
