Test/add onlineddl scheduler test (#337)
* test: add onlineddl scheduler test

Signed-off-by: <919179287@qq.com>

* test: alter ddl_strategy to mysql

Signed-off-by: <919179287@qq.com>

* fix: typo

Signed-off-by: <919179287@qq.com>

* test: remove testcast which about vitess mode

Signed-off-by: <919179287@qq.com>

* test: add onlineDDL e2e test

Signed-off-by: <919179287@qq.com>

* test: move onlineddl scheduler yaml into workflow

Signed-off-by: <919179287@qq.com>

* test: rm e2e log

Signed-off-by: <919179287@qq.com>

* test: rename onlineDDL e2e test

Signed-off-by: <919179287@qq.com>

* test: rename onlineDDL scheduler group name

Signed-off-by: <919179287@qq.com>

* test: format onlineDDL scheduler yaml

Signed-off-by: <919179287@qq.com>

* test: rename scheduler yaml name to OnlineDDL scheduler

Signed-off-by: <919179287@qq.com>

* test: modify ddlstrategy from mysql to vitess

Signed-off-by: <919179287@qq.com>

* test: add more onlineddl_scheduler_test

Signed-off-by: <919179287@qq.com>

* test: remove Idempotent submission e2e testcase

Signed-off-by: <919179287@qq.com>

* test: add onlineddl_vrepl_mysql57 test

Signed-off-by: <919179287@qq.com>

* test: add Check test results

Signed-off-by: <919179287@qq.com>

* test: add start e2e test sh file

Signed-off-by: <919179287@qq.com>

* test: remove online ddl testcase via vtctl

Signed-off-by: <919179287@qq.com>

* test: modify shard to default '0';

Signed-off-by: <919179287@qq.com>

* test: fix vrepl e2e testcase

Signed-off-by: <919179287@qq.com>

* fix: add onlineddl testcase for mysql57 and mysql80

Signed-off-by: earayu <earayu@163.com>

---------

Signed-off-by: <919179287@qq.com>
Signed-off-by: earayu <earayu@163.com>
Co-authored-by: earayu <earayu@163.com>

diff --git a/.github/workflows/cluster_endtoend_onlineddl_vrepl.yml b/.github/workflows/cluster_endtoend_onlineddl_vrepl.yml
--- a/.github/workflows/cluster_endtoend_onlineddl_vrepl.yml
+++ b/.github/workflows/cluster_endtoend_onlineddl_vrepl.yml
@@ -1,14 +1,14 @@
 # DO NOT MODIFY: THIS FILE IS GENERATED USING "make generate_ci_workflows"
 
-name: EndToEnd Test
+name: Cluster (onlineddl_vrepl)
 on:
-  pull_request:
+#  pull_request:
   workflow_dispatch:
   push:
     branches:
       - main
 concurrency:
-  group: format('{0}-{1}', ${{ github.ref }}, 'Cluster (wesql)')
+  group: format('{0}-{1}', ${{ github.ref }}, 'Cluster (onlineddl_vrepl)')
   cancel-in-progress: true
 
 env:
@@ -16,7 +16,7 @@ env:
 
 jobs:
   build:
-    name: Run endtoend tests on Cluster (wesql)
+    name: Run endtoend tests on Cluster (onlineddl_vrepl)
     runs-on: ubuntu-22.04
 
     steps:
@@ -59,7 +59,8 @@ jobs:
             - 'tools/**'
             - 'config/**'
             - 'bootstrap.sh'
-            - '.github/workflows/cluster_endtoend_wesql.yml'
+            - '.github/workflows/cluster_endtoend_onlineddl_vrepl.yml'
+            - 'go/test/endtoend/onlineddl/vrepl_suite/testdata'
 
     - name: Set up Go
       if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true'
@@ -114,29 +115,27 @@ jobs:
         source build.env
 
         set -x
-        
-        make failpoint-enable
-        chmod 755 ./test/failpoint/failpoints.sh && source ./test/failpoint/failpoints.sh
 
         # run the tests however you normally do, then produce a JUnit XML file
-        eatmydata -- go run test.go -docker=false -follow -shard wesql | tee -a output.txt | go-junit-report -set-exit-code > report.xml
-        make failpoint-disable
+        eatmydata -- go run test.go -docker=false -follow -shard onlineddl_vrepl | tee -a output.txt | go-junit-report -set-exit-code > report.xml
 
     - name: Print test output and Record test result
       if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true' && always()
       run: |
+
         # print test output
         cat output.txt
+
     - name: Check test results
       if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.end_to_end == 'true' && always()
       run: |
-          # check if any test failed
-          if grep -q -- '--- FAIL' output.txt; then
-              echo "Testcase is failed"
-              exit 1
-          elif grep -q -- 'FAIL	vitess.io' output.txt; then
-              echo "Testcase is failed"
-              exit 1
-          else
-              echo "Testcase is successful"
-          fi
+        # check if any test failed
+        if grep -q -- '--- FAIL' output.txt; then
+            echo "Testcase is failed"
+            exit 1
+        elif grep -q -- 'FAIL	vitess.io' output.txt; then
+            echo "Testcase is failed"
+            exit 1
+        else
+            echo "Testcase is successful"
+        fi
